#!/usr/bin/env bash

set -e
set -o pipefail
set -u

install_id="$INSTALL_ID"

timestamp=`date -Iminutes | sed 's/://g' | sed 's/-//g'`
tmp_dir="/tmp/$timestamp"
echo >&2 "fetching cloudwatch metrics..."

rds_cpu_query_file="/tmp/$timestamp-rds-cpu-query.json"
rds_cpu_query=$(cat <<EOF
{
   "StartTime" : "2025-03-11T00:17:00Z",
   "EndTime" : "2025-03-11T00:20:50Z",
   "MetricDataQueries" : [{
     "Id" : "cpu",
     "MetricStat" : {
     "Metric" : {
         "Namespace" : "AWS/RDS",
         "MetricName" : "CPUUtilization",
         "Dimensions" : [{ "Name" : "DBInstanceIdentifier" , "Value" : "$install_id"}]
     },
     "Period" : 360,
       "Stat" : "Minimum"
     }
   }]
}
EOF)
echo $rds_cpu_query > $rds_cpu_query_file
rds_cpu=`aws cloudwatch get-metric-data --cli-input-json "file://$rds_cpu_query_file"`
outputs=`jq --null-input --argjson rdsCpuJson "$rds_cpu" '{"rds_cpu": $rdsCpuJson}'`
echo $outputs >> $NUON_ACTIONS_OUTPUT_FILEPATH
