name       = "alb"
type       = "helm_chart"
chart_name = "alb-public-ingress"

[public_repo]
repo      = "nuonco/components"
directory = "aws/alb"
branch    = "main"

[values]
service_name       = "whoami"
service_port       = "80"
install_name       = "{{.nuon.install.id}}"
domain_certificate = "{{.nuon.components.wildcard_certificate.outputs.public_domain_certificate_arn}}"
domain             = "whoami.{{.nuon.install.sandbox.outputs.public_domain.name}}"
healthcheck_path   = "/health"
