name       = "alb_deepseek"
type       = "helm_chart"
chart_name = "deepseek-public-ingress"

[public_repo]
repo      = "nuonco/components"
directory = "aws/alb"
branch    = "main"

[values]
service_name       = "vllm-deepseek-vllm-chart"
service_port       = "80"
install_name       = "deepseek"
domain_certificate = "{{.nuon.components.wildcard_certificate.outputs.public_domain_certificate_arn}}"
domain             = "ds.{{.nuon.install.sandbox.outputs.public_domain.name}}"
healthcheck_path   = "/health"
