name       = "chat_api_image"
type       = "docker_build"
dockerfile = "Dockerfile"

[public_repo]
repo      = "nuonco/demo"
directory = "kitchen-sink/src/chat-api"
branch    = "fd/kitchen-sink/migrate-over"
