nAme       = "deepseek_chat_ui"
type       = "helm_chart"
chart_name = "deepseek-chat-ui"

[public_repo]
repo      = "nuonco/demo"
directory = "kitchen-sink/src/chat-ui"
branch    = "main"

[[values_file]]
source = "./values/deepseek_chat_ui.values.yaml"
