name              = "clickhouse_operator"
type              = "terraform_module"
terraform_version = "1.10.4"

[public_repo]
repo      = "nuonco/demo"
directory = "kitchen-sink/src/clickhouse_operator"
branch    = "main"

[vars]
cluster_name     = "{{.nuon.install.sandbox.outputs.cluster.name}}"
iam_role_arn     = "{{.nuon.install.sandbox.outputs.runner.runner_iam_role_arn}}"
operator_version = "0.24.4"
