name = "deepseek_namespace"
type = "terraform_module"
terraform_version = "1.10.4"

[public_repo]
repo      = "nuonco/components"
directory = "aws/kubectl-manifest"
branch    = "main"

[vars]
install_name = "{{.nuon.install.id}}"
cluster_name = "{{.nuon.install.sandbox.outputs.cluster.name}}"
iam_role_arn = "{{.nuon.install.sandbox.outputs.runner.runner_iam_role_arn}}"
yaml_body = """
---
apiVersion: v1
kind: Namespace
metadata:
  name: deepseek
"""
