name              = "external_secrets"
type              = "terraform_module"
terraform_version = "1.10.4"

[public_repo]
repo      = "nuonco/demo"
directory = "kitchen-sink/src/external_secrets"
branch    = "main"

[vars]
region       = "{{.nuon.install.sandbox.outputs.account.region}}"
cluster_name = "{{.nuon.install.sandbox.outputs.cluster.name}}"
iam_role_arn = "{{.nuon.install.sandbox.outputs.runner.runner_iam_role_arn}}"
install_id   = "{{.nuon.install.id}}"
