name              = "nodepool_neuron"
type              = "terraform_module"
terraform_version = "1.10.4"

[public_repo]
repo      = "nuonco/components"
directory = "aws/kubectl-manifest"
branch    = "main"

[vars]
install_name = "{{.nuon.install.id}}"
cluster_name = "{{.nuon.install.sandbox.outputs.cluster.name}}"
iam_role_arn = "{{.nuon.install.sandbox.outputs.runner.runner_iam_role_arn}}"
yaml_body = """
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: neuron
spec:
  disruption:
    budgets:
    - nodes: "1"
    consolidateAfter: 5m
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 1000
    memory: 1000Gi
  template:
    spec:
      expireAfter: 360h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: neuron
      taints:
        - key: "pool.nuon.co"
          operator: "Equal"
          value: "neuron"
          effect: "NoSchedule"
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - inf2.8xlarge
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - us-east-2a
        - us-east-2b
        - us-east-2c
"""
