name              = "nodeclass_neuron"
type              = "terraform_module"
terraform_version = "1.10.4"

[public_repo]
repo      = "nuonco/components"
directory = "aws/kubectl-manifest"
branch    = "main"

[vars]
install_name = "{{.nuon.install.id}}"
cluster_name = "{{.nuon.install.sandbox.outputs.cluster.name}}"
iam_role_arn = "{{.nuon.install.sandbox.outputs.runner.runner_iam_role_arn}}"
# hardcoded role and install id but that can be passed in as an input
yaml_body = """
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: neuron
spec:
  amiSelectorTerms:
    - alias: al2@latest
  instanceProfile: KarpenterNodeInstanceProfile-{{ .nuon.install.id }}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .nuon.install.id }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .nuon.install.id }}
  tags:
    karpenter.sh/discovery: {{ .nuon.install.id }}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        iops: 10000
        deleteOnTermination: true
        throughput: 125
"""
