#:schema https://api.nuon.co/v1/general/config-schema?source=terraform
name              = "rds_subnet"
type              = "terraform_module"
terraform_version = "1.10.4"

[public_repo]
repo      = "nuonco/demo"
directory = "kitchen-sink/src/rds_subnet"
branch    = "fd/kitchen-sink/migrate-over"

[vars]
# aws details
region             = "{{ .nuon.install.sandbox.outputs.account.region }}"
private_subnet_ids = "{{ index .nuon.install.sandbox.outputs.vpc.private_subnet_ids 0}},{{ index .nuon.install.sandbox.outputs.vpc.private_subnet_ids 1 }},{{ index .nuon.install.sandbox.outputs.vpc.private_subnet_ids 2 }}"
# rds subnet details
install_id              = "{{.nuon.install.id}}"
rds_subnet_name         = "rds-subnet-{{.nuon.install.id}}"
rds_subnet_display_name = "RDS Subnet {{.nuon.install.id}}"
