name              = "rds_cluster"
type              = "terraform_module"
terraform_version = "1.10.4"

[public_repo]
directory = "aws/rds-cluster"
repo      = "nuonco/components"
branch    = "fd/rds-cluster/switch-to-managed-password"

[vars]
port            = "5432"
identifier      = "{{ .nuon.install.id }}"
db_name         = "{{ .nuon.install.inputs.db_name }}"
instance_class  = "{{ .nuon.install.inputs.instance_class }}"
db_user         = "production"
subnet_group_id = "{{ .nuon.components.rds_subnet.outputs.id }}"
security_group  = "{{ .nuon.install.sandbox.outputs.vpc.default_security_group_id }}"
vpc_id          = "{{ .nuon.install.sandbox.outputs.vpc.id }}"
subnet_ids      = "{{ index .nuon.install.sandbox.outputs.vpc.private_subnet_ids 0}},{{ index .nuon.install.sandbox.outputs.vpc.private_subnet_ids 1 }},{{ index .nuon.install.sandbox.outputs.vpc.private_subnet_ids 2 }}"
