name = "vllm_deepseek"
type = "helm_chart"
chart_name = "vllm-deepseek"

[public_repo]
repo      = "aws-samples/deepseek-using-vllm-on-eks"
directory = "vllm-chart"
branch    = "main"

[[values_file]]
source = "./values/vllm_deepseek.values.yaml"
