image:
  repository: "{{ .nuon.components.chat_api_image.image.repository.uri }}"
  tag: "{{ .nuon.components.chat_api_image.image.tag }}"

configs:
  debug: "false"
  host: "0.0.0.0"
  port: 9021
  env: "prod"
  deepseek_api_url: "http://vllm-deepseek-vllm-chart.deepseek.svc.cluster.local"
  database_url: "psql://postgres:postgres@postgres:5432/postgres"

  clickhouse_host: "clickhouse-chat-api.default.svc.cluster.local"
  clickhouse_port: 9000
  clickhouse_username: "chat_api"
  clickhouse_password: "chat_api"
