namespace: deepseek
replicaCount: 1

containerPort: 8000

image:
  repository: "{{ .nuon.components.vllm_neuron_image.image.repository.uri }}"
  tag: "{{ .nuon.components.vllm_neuron_image.image.tag }}"
  pullPolicy: IfNotPresent

tolerations:
  - key: "pool.nuon.co"
    operator: "Equal"
    value: "neuron"
    effect: "NoSchedule"
  - key: "aws.amazon.com/neuron"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

command: "vllm serve deepseek-ai/DeepSeek-R1-Distill-Llama-8B --device neuron --tensor-parallel-size 2 --max-num-seqs 4 --block-size 8 --use-v2-block-manager --max-model-len 2048"

env:
  - name: NEURON_RT_NUM_CORES
    value: "2"
  - name: NEURON_RT_VISIBLE_CORES
    value: "0,1"
  - name: VLLM_LOGGING_LEVEL
    value: "INFO"

resources:
  limits:
    cpu: "30"
    memory: 64G
    aws.amazon.com/neuron: "1"
  requests:
    cpu: "30"
    memory: 64G
    aws.amazon.com/neuron: "1"

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 1800
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 1800
  periodSeconds: 5
