#:schema https://api.nuon.co/v1/general/config-schema?source=installer
name              = "Nuon Demo Installer"
description       = "Installer for the Nuon Demo App."
documentation_url = "https://docs.nuon.co/quickstart"
community_url     = "https://nuon-byoc.slack.com/ssb/redirect"
homepage_url      = "https://nuon.co"
github_url        = "https://github.com/nuonco"
logo_url          = "https://nuon.co/_astro/logo.PEcNPe73_Z1ISTvP.svg"
demo_url          = "https://www.youtube.com/embed/ajYyrTTYmpc?si=2FyF3Sq9bxuKZkfS"
favicon_url       = "https://nuon.co/_astro/apple-touch-icon.CB8rPL88.png"

# optional fields
og_image_url          = ""
copyright_markdown    = "© Nuon 2024"
footer_markdown       = """
[Terms of Service](https://nuon.co/terms) | [Docs](https://docs.nuon.co/get-started/introduction) | [Github][github.com/nuon](https://github.com/nuon)"
"""
post_install_markdown = """
# Demo App

{{.nuon.app.name}} is being deployed to your cloud. Once it's live, you can see the app running at [{{.nuon.install.inputs.service_name}}.{{.nuon.install.id}}.nuon.run](https://{{.nuon.install.inputs.service_name}}.{{.nuon.install.id}}.nuon.run)
"""
apps = [
    'appp8wgwu816ypus1aadcg875s',
    'apparhowpzogsf4emsproqbutc'
]
