#:schema https://api.nuon.co/v1/general/config-schema

version = "v1"
description = "Deploy an app to ECS in it's own VPC."
display_name = "Stand-Alone ECS Deployment"

[inputs]
source = "app_inputs.toml"

[runner]
runner_type = "aws-ecs"

[sandbox]
terraform_version = "1.7.5"
[sandbox.public_repo]
directory = "aws-ecs"
repo      = "nuonco/sandboxes"
branch    = "main"

[[components]]
source = "components/container_image.toml"

[[components]]
source = "components/ecs_service.toml"
