image:
  repository: ""
  tag: ""

configs:
  debug: "false"
  host: "localhost"
  port: 9021
  env: "prod"
  deepseek_api_url: "vllm-deepseek-vllm-chart.deepseek.svc.cluster.local"
  database_url: "psql://postgres:postgres@postgres:5432/postgres"
  clickhouse_host: 'clickhouse-pv-simple.default.svc.cluster.local'
  clickhouse_port: 9000
  clickhouse_username: "chat_api"
  clickhouse_password: "chat_api"
