[[role]]
name                 = "{{ .nuon.install.id }}-eks-simple-break-glass"
description          = "grant access to the sandbox for install {{ .nuon.install.id }}"
display_name         = "Sandbox Break Glass for Install {{ .nuon.install.id }}"
permissions_boundary = ""

[[role.policies]]
managed_policy_name = "AdministratorAccess"

[[role.policies]]
name = "{{ .nuon.install.id }}-remove-secrets-manager"
contents = """
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "DenySecretsManagerAccess",
            "Effect": "Deny",
            "Action": [
                "secretsmanager:*"
            ],
            "Resource": "*"
        }
    ]
}
"""
