#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "cloudwatch"
timeout = "5m0s"

[[triggers]]
type = "manual"

[[steps]]
name    = "diagnose"
command = "./diagnose"

[steps.public_repo]
repo      = "nuonco/demo"
directory = "kitchen-sink/src/diagnose"
branch    = "main"
