#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "gen_secrets"
timeout = "1m30s"


[[triggers]]
type = "pre-deploy"

[[triggers]]
type = "manual"

[[steps]]
name    = "generate secrets"
command = "./gen_secrets"

[steps.public_repo]
repo      = "nuonco/demo"
directory = "kitchen-sink/src/actions"
branch    = "fd/add-secret-gen-pre-deploy-action"

[steps.env_vars]
REGENERATE      = "false"
NUON_INSTALL_ID = "{{ .nuon.install.id }}"
