#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "kubectl_deployment_restart"
timeout = "0m15s"

[[triggers]]
type = "manual"

[[steps]]
name    = "deployment-restart"
command = "./deployment-restart"

[steps.public_repo]
repo      = "nuonco/actions"
branch    = "fd/kube/restart-deployment"
directory = "kube"

[steps.env_vars]
DEPLOYMENT_NAME      = "chat-api"
DEPLOYMENT_NAMESPACE = "deepseek"
