#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "whoami_alb_healthcheck"
timeout = "0m30s"

[[triggers]]
type          = "cron"
cron_schedule = "*/30 */1 * * *"

[[triggers]]
type = "manual"

[[steps]]
name    = "healthcheck"
command = "./alb-healthcheck"

[steps.public_repo]
repo      = "nuonco/actions"
branch    = "main"
directory = "aws"

[steps.env_vars]
INGRESS_NAME      = "{{.nuon.install.id}}-public"
INGRESS_NAMESPACE = "{{.nuon.install.id}}"
