#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "whoami_http_healthcheck"
timeout = "0m30s"

[[triggers]]
type          = "cron"
cron_schedule = "*/15 * * * *"

[[triggers]]
type = "manual"

[[steps]]
name    = "healthcheck"
command = "./healthcheck"

[steps.public_repo]
repo      = "nuonco/actions"
branch    = "main"
directory = "common"

[steps.env_vars]
ENDPOINT             = "https://whoami.{{.nuon.install.id}}.nuon.run/ready"
METHOD               = "HEAD"
EXPECTED_STATUS_CODE = "200"
