#:schema https://api.nuon.co/v1/general/config-schema?source=runner
runner_type     = "aws"
helm_driver     = "configmap"
init_script_url = "https://raw.githubusercontent.com/nuonco/runner/refs/heads/fd/feat/runner-mng-mode-init/scripts/aws/init-mng.sh"

[env_vars]
foo = "bar"
