apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
          requests:
            cpu: "1"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /get
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /get
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
