---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-api-config
  namespace: deepseek
data:
  {{- range $key, $value := .Values.configs }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
