apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-api
  namespace: deepseek
  labels:
    app: chat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-api
  template:
    metadata:
      labels:
        app: chat-api
    spec:
      containers:
      - name: chat-api
        image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
        command: ["/bin/sh","-c"]
        args: ["pip install uv; uv sync; uv run python main.py"]  # idk why we had to do this
        ports:
        - containerPort: 7860
        envFrom:
        - configMapRef:
            name: chat-api-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
