---
apiVersion: v1
kind: Service
metadata:
  name: chat-api-service
  namespace: deepseek
spec:
  selector:
    app: chat-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9021
  type: ClusterIP
