#:schema https://api.nuon.co/v1/general/config-schema?source=inputs
[[group]]
name         = "app"
description  = "Configure HTTPBin."
display_name = "App Configuration"

[[input]]
name         = "service_name"
description  = "What to name the ECS service.Will be used to create DNS records."
default      = "httpbin"
sensitive    = false
display_name = "Service Name"
group        = "app"

[[input]]
name         = "display_name"
description  = "A display name for the service"
default      = "HTTPBin"
sensitive    = false
display_name = "Display Name"
group        = "app"
