#!/usr/bin/env bash

set -e
set -o pipefail
set -u

# no pager
export AWS_PAGER=""

# env vars
install_id="$NUON_INSTALL_ID"
regenerate="$REGENERATE"

# derived constants
secret_name="gen/$install_id"
if [ "$REGENERATE" = "true" ];then
  echo >&2 "re generating secrets..."
  should_regenerate="true"
else
  echo >&2 "generating secrets (if they do not already exist)..."
  should_regenerate="false"
fi

# tmp dir
timestamp=`date -Iminutes | sed 's/://g' | sed 's/-//g'`
tmp_dir="/tmp/gen-secret/$timestamp"
mkdir -p $tmp_dir
tmp_loc="$tmp_dir/secret.json"

# retrieve secret object from secrets manager
candidates=`aws secretsmanager list-secrets --filter "Key=name,Values=$secret_name" --output=json`
secret_count=$(echo $candidates | jq '.SecretList | length')

if [ "$secret_count" -eq "0" ];then # if it does not exist, create it
  echo >&2 "secret does not exist - creating it"
  # generate some secrets
  cookie_secret=`openssl rand -hex 24`
  jwt_secret=`openssl rand -base64 45`
  # store the secrets in the temp file
  secret=`jq --null-input --arg cookie_secret_ "$cookie_secret" --arg jwt_secret_ "$jwt_secret" '{"cookie_secret": $cookie_secret_, "jwt_secret": $jwt_secret_}'`
  echo "$secret" > $tmp_loc
  # compose tags
  tags='{"Key": "nuon_install_id", "Value":"'"$install_id"'"}'
  # create secret from file
  aws secretsmanager create-secret --name "$secret_name" --tags "$tags" --secret-string "file://$tmp_loc"
  regenerated="false"
elif [[ "$secret_count" -eq "1" && "$should_regenerate" = "true" ]];then # if it does exist, and we should, regenerate it
  secret_id=`echo $candidates | jq '.SecretList[0].ARN'`
  echo >&2 "Secret does exist - regenerating $secret_id"
  # generate new secrets
  cookie_secret=`openssl rand -hex 24`
  jwt_secret=`openssl rand -base64 45`
  # store the secrets in the temp file
  secret=`jq --null-input --arg cookie_secret_ "$cookie_secret" --arg jwt_secret_ "$jwt_secret" '{"cookie_secret": $cookie_secret_, "jwt_secret": $jwt_secret_}'`
  echo "$secret" > $tmp_loc
  aws secretsmanager update-secret --secret-id "$secret_name" --secret-string "file://$tmp_loc"
  regenerated="true"
else # secret exists but we should not regenerate
  echo >&2 "Secret does exist - doing nothing"
  regenerated="false"
fi

secret=`aws secretsmanager list-secrets --filter "Key=name,Values=$secret_name" --output=json | jq '.SecretList[0]'`

# compose outputs
outputs=`jq --null-input --arg regenerated_ "$regenerated" --argjson secret_ "$secret" '{"secret": $secret_, "regenerated": $regenerated_}'`

# write outputs
echo $outputs >> $NUON_ACTIONS_OUTPUT_FILEPATH
