---
apiVersion: v1
kind: Secret
metadata:
  name: deepseek-chatbot-secrets
  namespace: deepseek
type: Opaque
stringData:
  admin-username: admin
  admin-password: c4f3b60c99c94f2fb18bf3e0557599e4674db53b93e9c30a
