#:schema https://api.nuon.co/v1/general/config-schema?source=docker_build

name       = "docker_image"
type       = "docker_build"
dockerfile = "Dockerfile"

[public_repo]
repo      = "nuonco/demo"
directory = "src/docker-image"
branch    = "main"
