apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: echo
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        resources:
          limits:
            cpu: ".25"
            memory: "128Mi"
          requests:
            cpu: ".1"
            memory: "64Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.deployment.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.deployment.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
