terraform_version = "1.11.3"

[public_repo]
directory = "aws-eks"
repo      = "nuonco/sandboxes"
branch    = "fd/exp/karpenter"

[vars]
cluster_version = "1.32"
# managed node group
default_instance_type = "t3a.medium"
min_size              = "2"
desired_size          = "4"
max_size              = "4"
