#:schema https://api.nuon.co/v1/general/config-schema?source=terraform
name      = "temporal_ai_agent_ingress"
type      = "kubernetes_manifest"
namespace = "temporal-ai-agent"

dependencies = ["temporal_ai_agent"]

manifest  = "./manifests/temporal_ai_agent_ingress.yaml"
