#:schema https://api.nuon.co/v1/general/config-schema?type=terraform
name              = "rds_subnet"
type              = "terraform_module"
terraform_version = "1.13.5"

[public_repo]
repo      = "nuonco/components"
directory = "aws/rds-subnet-v2"
branch    = "fd/rds-subnet-v2"

[vars]
# rds subnet details
vpc_id                  = "{{ .nuon.install_stack.outputs.vpc_id }}"
nuon_install_id         = "{{ .nuon.install.id }}"
rds_subnet_name         = "rds-subnet-inbox-zero-{{ .nuon.install.id }}"
rds_subnet_display_name = "RDS Subnet for inbox-zero install {{ .nuon.install.id }}"
region                  = "{{ .nuon.sandbox.outputs.account.region }}"
