name: sync
on:
  push:
    branches: main
    paths:
      - "nuon/**"
      - "src/**"
  workflow_dispatch:
defaults:
  run:
    shell: bash
env:
  NUON_ORG_ID: ${{ secrets.NUON_ORG_ID }}
  NUON_API_TOKEN: ${{ secrets.NUON_API_TOKEN }}
  NUON_API_URL: "https://api.nuon.co"
  NUON_FILE: ${{ secrets.NUON_FILE }}

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Release to Customers
    needs: sync
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: sync eks-simple
        uses: nuonco/actions-nuon@v1
        with:
          org_id: ${{ secrets.NUON_ORG_ID }}
          api_token: ${{ secrets.NUON_API_TOKEN }}
          api_url: "https://api.nuon.co"
          app_id: appnvpbof1axn6lhgnaj7gd87o
          command: "apps sync eks-simple"
      - name: sync eks-simple-subdomains
        uses: nuonco/actions-nuon@v1
        with:
          org_id: ${{ secrets.NUON_ORG_ID }}
          api_token: ${{ secrets.NUON_API_TOKEN }}
          api_url: "https://api.nuon.co"
          app_id: appa2hoi075j3qwvm99k83hpc6
          command: "apps sync eks-simple-subdomains"
