on:
  push:
    branches: main
    paths:
      - "nuon/**"
      - "src/**"
defaults:
  run:
    shell: bash
env:
  NUON_ORG_ID: ${{ secrets.NUON_ORG_ID }}
  NUON_API_TOKEN: ${{ secrets.NUON_API_TOKEN }}
  NUON_APP_ID: ${{ secrets.NUON_APP_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install CLI
        id: cli
        run: ./scripts/install-cli.sh
      - name: Sync configs
        id: sync
        run: nuon apps sync --all
        working-directory: ./nuon
      - name: Create releases
        id: release
        run: nuon components list -j | jq '.[].id' | xargs -n 1 nuon releases create --latest-build -c
